import = ["~/.config/alacritty/current-theme.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.75

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontMono"
style = "Italic"
